#include <Windows.h>
#include <windowsx.h>
#include <ShObjIdl.h>
#include <string>
#include <vector>
#include <memory>
#include "resource.h"
#include "Stat.h"
#include "Stats.h"
#include "WeaponStats.h"
#include "TotalStats.h"
#include "Weapon.h"
#include "WeaponType.h"
#include "WeaponList.h"
#include "WeaponTypeList.h"
#include "Class.h"
#include "ClassList.h"
#include "Student.h"
#include "Roster.h"
#include "ListViewTemplate.h"
#include "ListBoxTemplate.h"
#include "DropDownTemplate.h"
#include "ButtonTemplate.h"
#include "ListViewStats.h"
#include "ListViewWeaponStats.h"
#include "ListViewTotalStats.h"
#include "ListBoxCharNames.h"
#include "ListBoxClasses.h"
#include "ListBoxWeapons.h"
#include "DropDownWeaponTypes.h"
#include "ButtonClassBaseStats.h"
#include "ButtonClassBoostedStats.h"
#include "StatCalculator.h"
